name: Crear noticia

on:
  push:
    branches: [ main ]
    
env:
  REPO_NAME: nombre-de-tu-repositorio
  BRANCH_NAME: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_NAME }}

    - name: Copy plantilla.html
      run: cp plantilla/plantilla.html noticias/${{ github.event.head_commit.id }}.html

    - name: Modificar el archivo
      run: |
        sed -i "s/Fecha de la noticia/$(cat generador/${{ github.event.head_commit.added | grep -m1 .html }} | grep -oP '(?<=<fecha>).*(?=<\/fecha>)')/" noticias/${{ github.event.head_commit.id }}.html
        sed -i "s/Título de la noticia/$(cat generador/${{ github.event.head_commit.added | grep -m1 .html }} | grep -oP '(?<=<titulo>).*(?=<\/titulo>)')/" noticias/${{ github.event.head_commit.id }}.html
        sed -i "s/Género de la noticia/$(cat generador/${{ github.event.head_commit.added | grep -m1 .html }} | grep -oP '(?<=<genero>).*(?=<\/genero>)')/" noticias/${{ github.event.head_commit.id }}.html
        sed -i "s/Autor de la noticia/$(cat generador/${{ github.event.head_commit.added | grep -m1 .html }} | grep -oP '(?<=<autor>).*(?=<\/autor>)')/" noticias/${{ github.event.head_commit.id }}.html
        sed -i "s/noticia aquí/$(cat generador/${{ github.event.head_commit.added | grep -m1 .html }} | grep -oP '(?<=<contenido>).*(?=<\/contenido>)')/" noticias/${{ github.event.head_commit.id }}.html

    - name: Push cambios al repositorio
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ env.BRANCH_NAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ env.REPO_NAME }}
