name: Generar noticia

on:
  push:
    branches: [ main ]
    paths:
    - 'generador/*.html'
  
jobs:
  generar_noticia:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_PATH: 'plantilla/plantilla.html'
      NOTICIAS_PATH: 'noticias'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16.x'
      
    - name: Install dependencies
      run: npm install
      
    - name: Create news file
      run: |
        NEW_FILE=$(echo ${{ github.event.head_commit.added }} | grep -m1 .html)
        cp "${{ env.TEMPLATE_PATH }}" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        sed -i "s/Fecha de la noticia/$(grep -oP '(?<=<fecha>).*?(?=</fecha>)' ${{ env.NOTICIAS_PATH }}/$NEW_FILE)/g" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        sed -i "s/Título de la noticia/$(grep -oP '(?<=<titulo>).*?(?=</titulo>)' ${{ env.NOTICIAS_PATH }}/$NEW_FILE)/g" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        sed -i "s/Género de la noticia/$(grep -oP '(?<=<genero>).*?(?=</genero>)' ${{ env.NOTICIAS_PATH }}/$NEW_FILE)/g" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        sed -i "s/Autor de la noticia/$(grep -oP '(?<=<autor>).*?(?=</autor>)' ${{ env.NOTICIAS_PATH }}/$NEW_FILE)/g" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        sed -i "s/noticia aquí/$(grep -oP '(?<=<contenido>).*?(?=</contenido>)' ${{ env.NOTICIAS_PATH }}/$NEW_FILE)/g" "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
        git commit -m "Agregada noticia $NEW_FILE"
        git push
      
    - name: Cleanup
      run: |
        rm "${{ env.NOTICIAS_PATH }}/$NEW_FILE"
