name: Generador de noticias

on:
  push:
    paths:
      - 'generador/*.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy plantilla to noticias
      run: |
        cp plantilla/plantilla.html noticias/

    - name: Set event.json filename
      run: |
        echo "::set-env name=EVENT_FILENAME::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Generate event.json
      run: |
        echo "$(cat generador/${{ env.EVENT_FILENAME }})" > generador/event.json

    - name: Reemplazar contenido de plantilla con datos del archivo subido
      run: |
        sed -i "s/Fecha de la noticia/$(cat generador/event.json | grep -oP '(?<=<fecha>).*(?=<\/fecha>)')/" noticias/plantilla.html
        sed -i "s/Título de la noticia/$(cat generador/event.json | grep -oP '(?<=<titulo>).*(?=<\/titulo>)')/" noticias/plantilla.html
        sed -i "s/Género de la noticia/$(cat generador/event.json | grep -oP '(?<=<genero>).*(?=<\/genero>)')/" noticias/plantilla.html
        sed -i "s/Autor de la noticia/$(cat generador/event.json | grep -oP '(?<=<autor>).*(?=<\/autor>)')/" noticias/plantilla.html
        sed -i "s/noticia aquí/$(cat generador/event.json | grep -oP '(?<=<contenido>).*(?=<\/contenido>)')/" noticias/plantilla.html

    - name: Rename plantilla to file name
      run: |
        mv noticias/plantilla.html noticias/${{ env.EVENT_FILENAME }}.html

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update news for ${{ env.EVENT_FILENAME }}"
        commit_options: '--no-verify'
        branch: ${{ github.head_ref }}
        branch-suffix: '-generated'
        token: ${{ secrets.GITHUB_TOKEN }}
